import turtle
from turtle import*
from random import randint
bgcolor('black')
a=turtle.Turtle()
b=turtle.Turtle()
c=turtle.Turtle()
d=turtle.Turtle()
x=turtle.Turtle()
a.shape('turtle')
b.shape('turtle')
c.shape('turtle')
d.shape('turtle')
a.color('red')
b.color('blue')
c.color('green')
d.color('yellow')
x.color('white')
a.penup()
b.penup()
c.penup()
d.penup()
x.penup()
a.goto(-300,100)
b.goto(-300,50)
c.goto(-300,0)
d.goto(-300,-50)
x.goto(300,300)
a.pendown()
b.pendown()
c.pendown()
d.pendown()
x.pendown()
x.rt(90)
x.fd(600)
while x.xcor()>=a.xcor() and x.xcor()>=b.xcor() and x.xcor()>=c.xcor() and x.xcor()>=d.xcor():
    a.penup()
    a.fd(randint(1,10))
    a.pendown()
    b.penup()
    b.fd(randint(1,10))
    b.pendown()
    c.penup()
    c.fd(randint(1,10))
    c.pendown()
    d.penup()
    d.fd(randint(1,10))
    d.pendown()
if a.xcor()>x.xcor():
    a.circle(100)
elif b.xcor()>x.xcor():
    b.circle(100)
elif c.xcor()>x.xcor():
    c.circle(100)
else:
    d.circle(100)
exitonclick()

